### ISSUE TITLE
Presentation displays blank page on Windows

### ISSUE THREAD

**Issue by shreyasbharath** [sebald/melodrama#8]
I installed Melodrama and created a new presentation, chose the nova theme and syntax highlighting during bootstrapping.

When I run `npm start`, it compiles fine and the page opens up on my browser. However it is simply a blank white page.

How do I fix this? I am using NodeJS v8.0.0 on Windows 10.

**Comment by sebald** [comment]
Could you please provide more information? It's hard to reproduce with the given information.

Is there any `console` output when you see the blank page?

**Comment by shreyasbharath** [comment]
Output of `npm start --verbose`. There's nothing being output to the console when the blank page is displayed, which is strange.

I should mention that I have tried this on two machines today, one a Windows 7 one and this one is running Windows 10.

```
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'start',
npm verb cli   '--verbose' ]
npm info using npm@5.0.3
npm info using node@v8.0.0
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle melodrama-example-presentation@1.0.0~prestart: melodrama-example-presentation@1.0.0
npm info lifecycle melodrama-example-presentation@1.0.0~start: melodrama-example-presentation@1.0.0

> melodrama-example-presentation@1.0.0 start C:\Users\shrey\Desktop\melodrama-example-presentation
> melodrama-scripts start index.js

i Starting server @ http://localhost:3001!
√ Compilation done! (50.5s, 5.36 MB)
```

And here's what it looks like -
![output](https://cloud.githubusercontent.com/assets/1886010/26820314/8ce66480-4af6-11e7-96a8-f681abecc55e.png)

Does this help at all? How can I provide more information to help diagnose this bug?

**Comment by sebald** [comment]
Sorry, I meant the `console` of your browser :)

Anyway, since `Spectacle` 2.0 the API has changed + the (underlying) `babel` dependency was not correctly set to a fixed version.

I will try to fix this today. Sorry for any inconvenience.

**Comment by shreyasbharath** [comment]
Ah, sorry I misunderstood. I am new to JavaScript / Node JS (my background is C/C++).

Here's the output from the browser -
![console](https://cloud.githubusercontent.com/assets/1886010/26821492/b2f8f346-4afa-11e7-9ab9-607da0457323.png)

It does look like something to do with `babel` as you mentioned.

**Comment by sebald** [comment]
@shreyasbharath 

> Ah, sorry I misunderstood. I am new to JavaScript / Node JS (my background is C/C++).

Welcome to the wonderful world of JS then 🎉🙂

**Comment by sebald** [comment]
@shreyasbharath Can you please update to the latest version of `melodrama-scripts`? Either make a new presentation with `melodrama` or do a `npm i melodrama-scripts@latest` in the existing project.

**Comment by shreyasbharath** [comment]
@sebald All good now! Thanks for your help :)
